"""add player profile fields

Revision ID: 3e048b74dde2
Revises: a48ba577e9db
Create Date: 2026-09-13 00:22:03.193525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e048b74dde2'
down_revision: Union[str, Sequence[str], None] = 'a48ba577e9db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('preferred_foot', sa.String(length=20), nullable=True))
    op.add_column('players', sa.Column('shirt_number', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('players', sa.Column('nationality', sa.String(length=100), nullable=True))
    op.add_column('players', sa.Column('phone', sa.String(length=30), nullable=True))
    op.add_column('players', sa.Column('email', sa.String(length=150), nullable=True))
    op.add_column('players', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('players', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('weight', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('joined_date', sa.Date(), nullable=True))
    op.add_column('players', sa.Column('profile_image', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'profile_image')
    op.drop_column('players', 'joined_date')
    op.drop_column('players', 'weight')
    op.drop_column('players', 'height')
    op.drop_column('players', 'bio')
    op.drop_column('players', 'email')
    op.drop_column('players', 'phone')
    op.drop_column('players', 'nationality')
    op.drop_column('players', 'date_of_birth')
    op.drop_column('players', 'shirt_number')
    op.drop_column('players', 'preferred_foot')
    # ### end Alembic commands ###
