"""add player status

Revision ID: 456f028277df
Revises: 2b2ca5d91bc1
Create Date: 2026-08-19 17:10:16.285450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '456f028277df'
down_revision: Union[str, Sequence[str], None] = '2b2ca5d91bc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('status', sa.String(length=20), nullable=False, server_default='Active'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'status')
    # ### end Alembic commands ###
