"""add starter status to match squad

Revision ID: 9c46daae44e1
Revises: 5ce982d74a1a
Create Date: 2026-08-30 18:49:05.613330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c46daae44e1'
down_revision: Union[str, Sequence[str], None] = '5ce982d74a1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'match_squads', 
        sa.Column(
            'is_starter', 
            sa.Boolean(), 
            nullable=False, 
            server_default=sa.false(),
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_squads', 'is_starter')
    # ### end Alembic commands ###
