"""add related player to match events

Revision ID: a48ba577e9db
Revises: 9c46daae44e1
Create Date: 2026-09-02 23:01:47.787647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a48ba577e9db'
down_revision: Union[str, Sequence[str], None] = '9c46daae44e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_events', sa.Column('related_player_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'match_events', 'players', ['related_player_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'match_events', type_='foreignkey')
    op.drop_column('match_events', 'related_player_id')
    # ### end Alembic commands ###
