"""create matches table

Revision ID: e4f584b97e8e
Revises: 456f028277df
Create Date: 2026-08-23 00:50:53.989326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4f584b97e8e'
down_revision: Union[str, Sequence[str], None] = '456f028277df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('opponent_name', sa.String(length=100), nullable=False),
    sa.Column('match_date', sa.DateTime(), nullable=False),
    sa.Column('competition', sa.String(length=100), nullable=False),
    sa.Column('venue', sa.String(length=100), nullable=True),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('our_score', sa.Integer(), nullable=False),
    sa.Column('opponent_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    # ### end Alembic commands ###
