"""create training session coaches table

Revision ID: f695e88bdf96
Revises: bb68ca1dff42
Create Date: 2026-09-24 23:23:47.556026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f695e88bdf96'
down_revision: Union[str, Sequence[str], None] = 'bb68ca1dff42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_session_coaches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('training_session_id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ),
    sa.ForeignKeyConstraint(['training_session_id'], ['training_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('training_session_id', 'coach_id', name='uq_training_session_coach')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_session_coaches')
    # ### end Alembic commands ###
